export { default as App } from './App';
export { default as Home } from './Home';
export { default as Content } from './Content';
export { default as Schools } from './Schools';
export { default as Header } from './Header';
export { default as AuthForm } from './AuthForm';
export { default as StudentForm } from './StudentForm';
export { default as SchoolForm } from './SchoolForm';
export { default as NotFound } from './NotFound';
